version: '3.8'

networks:
  nbank-network:
    name: nbank-network

services:
  backend:
    image: nobugsme/nbank:with_username_error_fix
    container_name: nbank-backend
    ports:
      - "4111:4111"
    networks:
      - nbank-network


  frontend:
    image: nobugsme/nbank-ui:latest
    container_name: nbank-frontend
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - nbank-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - nbank-network



